### ISSUE TITLE
[Issue#11][Функционал приложения] Сохранение списка задач

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#11]
Добавить сохранение текущего списка задач, с которым работает пользователь, в файл.

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#11][Функционал приложения]

**Comment by Veleri** [comment]
В какой из файлов сохраняется список задач? Рекомендую, чтобы пользователь задавал значение файла.

**Comment by SummertimeS4dness** [comment]
Список сохраняется в файл, который выбран в начале работы с программой

**Comment by Veleri** [comment]
Рекомендую, чтобы пользователь задавал значение файла т.к. приложение имеет функционал сохранения текущего состояния.

**Comment by SummertimeS4dness** [comment]
Коммит "[Issue#11][Функционал приложения] доработка"
