### ISSUE TITLE
[Issue#2][Код] Java Code Conventions

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#13]
Пересмотреть код на соответствие Java Code Conventions.

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#2][Код]. Есть много замечаний от чекстайла, но почти все они "line continuation have incorrect indentation level..."

**Comment by SummertimeS4dness** [comment]
Была небольшая ошибка, буквально 2 строки, исправлено тут [Issue#2][Код] дополнительный
