### ISSUE TITLE
[Issue#3][Код] Авторство классов

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#14]
Авторы класса "JavaConsole " : @author RJHM van den Bergh , rvdb@comweb.nl. Нельзя полностью копировать чужой класс. Можно взять его за основу и доработать. Поправь авторство в этом классе, с указанием своих доработок в теге @history.
Точно такая же ситуация и с другими классами, например "Menu". Для выполнения л/р необходимо самостоятельно разрабатывать классы.

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#3][Код] Доработка классов была произведена во время работы над программой и другими правками

**Comment by Veleri** [comment]
Интерфейс "MenuCallback"
@author David MacDermot
 @date 02-07-2012

**Comment by SummertimeS4dness** [comment]
Коммит "[Issue#3][Код] доработка"
