### ISSUE TITLE
[Issue#4][Код] Модификаторы доступа

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#15]
Для всех полей добавить модификаторы доступа.

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#4][Код]

**Comment by Veleri** [comment]
Нужно добавить модификатор доступа для "logger ":
final static Logger logger = Logger.getLogger(MainController.class);

**Comment by SummertimeS4dness** [comment]
Коммит "[Issue#4][Код] доработка"
