### ISSUE TITLE
[Issue#6][Код] Обработка ошибок

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#17]
При обработке ошибок в лог следует передавать саму ошибку, например:
- logger.error("Error",e1);

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#6][Код]

**Comment by Veleri** [comment]
Необходимо исправить все подобные обработки ошибок:
catch (FileNotFoundException e) {
                e.printStackTrace();
            }

**Comment by Veleri** [comment]
А также (класс class Menu):
 catch (Exception e1) {
        }

**Comment by SummertimeS4dness** [comment]
Коммит "[Issue#6][Код] доработка"
