### ISSUE TITLE
[Issue#8][Код] Вложенность

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#19]
Слишком много переменных отвечающих за возврат в предыдущие меню. Пока вложенность приемлема достаточно 3-х переменных, а что же будет с вложенностью 10, 12?

**Comment by SummertimeS4dness** [comment]
[Issue#8][Код] Вложенности больше нет, кроме одного места(календарь), там всего лишь 2 уровня и без нее не обойтись
